DROP TABLE IF EXISTS BBS;
CREATE TABLE BBS (
BBS_NUM INT AUTO_INCREMENT PRIMARY KEY,
WRITER VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
TITLE VARCHAR(150) NOT NULL,
CONTENTS VARCHAR(2048) NOT NULL,
REGDATE DATE NOT NULL
);
COMMIT;